#!/usr/bin/env bash
# Export one state's DENUE layer as a self-contained, portable .sql.gz that any
# empty PostGIS instance can restore in one shot:
#
#     createdb mexico
#     psql -d mexico -c "CREATE EXTENSION postgis;"
#     gunzip -c denue_24.sql.gz | psql -d mexico
#
# The dump includes:
#   - `CREATE SCHEMA IF NOT EXISTS gis;`
#   - The 3 base tables (gis_dataset, gis_layer, gis_feature) — idempotent
#   - GIST index on gis.gis_feature.geom
#   - The dataset + layer parent rows for this state
#   - All feature rows for the layer (via COPY through a temp staging table)
#   - `VACUUM ANALYZE gis.gis_feature;`
#
# This is deliberately *not* a `pg_dump` — pg_dump output is brittle across PG
# major versions, leaks `set_config('search_path','',false)`, and assumes a
# specific role exists on the destination. The hand-rolled form is portable.
#
# Usage:
#   ./export_state_dump.sh 24       → dist/denue_24.sql.gz
#   ./export_state_dump.sh 24 plain → dist/denue_24.sql (uncompressed, for inspection)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

CODE="${1:?usage: $0 <state-code 01..32> [plain]}"
FORMAT="${2:-gz}"
state_ids "$CODE"

require_container

step "Export DENUE ${CODE} (${STATE_NAME}) → portable .sql"

COUNT=$(psql_in -tA -c "SELECT feature_count FROM gis.gis_layer WHERE id='${LAYER_ID}';" 2>/dev/null || echo 0)
[[ "$COUNT" -gt 0 ]] || fail "layer ${LAYER_ID} has 0 features locally — import first"
ok "rows to export: $COUNT"

OUT_BASE="$GIS_DIST_DIR/denue_${CODE}"
PLAIN="$OUT_BASE.sql"
GZ="$OUT_BASE.sql.gz"
rm -f "$PLAIN" "$GZ"

step "Write header (schema bootstrap + parent rows)"
{
  cat <<HDR
-- =====================================================================
-- DENUE — ${STATE_NAME} (${VINTAGE})
-- Generated by docuget-gis-data ($(date -u +%Y-%m-%dT%H:%M:%SZ))
--
-- Source: INEGI. Directorio Estadístico Nacional de Unidades Económicas
--         (DENUE). Términos de Libre Uso.
--         https://www.inegi.org.mx/inegi/terminos.html
--
-- Restore into an empty database with PostGIS installed:
--     CREATE DATABASE mexico;
--     \\connect mexico
--     CREATE EXTENSION IF NOT EXISTS postgis;
--     \\i denue_${CODE}.sql
-- =====================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS gis;
SET search_path = public, gis;

CREATE TABLE IF NOT EXISTS gis.gis_dataset (
  id          text PRIMARY KEY,
  company_id  text NOT NULL DEFAULT 'public',
  slug        text NOT NULL,
  name        text NOT NULL,
  source      text NOT NULL,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, slug)
);

CREATE TABLE IF NOT EXISTS gis.gis_layer (
  id              text PRIMARY KEY,
  dataset_id      text NOT NULL REFERENCES gis.gis_dataset(id) ON DELETE CASCADE,
  name            text NOT NULL,
  geometry_type   text NOT NULL,
  srid            int  NOT NULL DEFAULT 4326,
  schema          jsonb NOT NULL DEFAULT '{}'::jsonb,
  feature_count   bigint NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gis.gis_feature (
  id          bigserial PRIMARY KEY,
  layer_id    text NOT NULL REFERENCES gis.gis_layer(id) ON DELETE CASCADE,
  geom        geometry(Geometry, 4326),
  props       jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS gis_feature_geom_gix    ON gis.gis_feature USING GIST (geom);
CREATE INDEX IF NOT EXISTS gis_feature_layer_idx   ON gis.gis_feature (layer_id);

-- Idempotent restore: drop any prior rows for this state.
DELETE FROM gis.gis_feature WHERE layer_id = '${LAYER_ID}';
DELETE FROM gis.gis_layer   WHERE id       = '${LAYER_ID}';
DELETE FROM gis.gis_dataset WHERE id       = '${DATASET_ID}';

HDR

  # Parent rows: dataset then layer, regenerated from the live PG using format()
  # so we don't have to escape JSON manually.
  psql_in -tA -c "
    SELECT format(
      \$Q\$INSERT INTO gis.gis_dataset (id, company_id, slug, name, source, metadata)
         VALUES (%L, %L, %L, %L, %L, %L::jsonb);\$Q\$,
      d.id, d.company_id, d.slug, d.name, d.source, d.metadata::text)
    FROM gis.gis_dataset d
    JOIN gis.gis_layer l ON l.dataset_id = d.id
    WHERE l.id = '${LAYER_ID}';
  "

  psql_in -tA -c "
    SELECT format(
      \$Q\$INSERT INTO gis.gis_layer (id, dataset_id, name, geometry_type, srid, schema, feature_count)
         VALUES (%L, %L, %L, %L, %s, %L::jsonb, %s);\$Q\$,
      id, dataset_id, name, geometry_type, srid, schema::text, feature_count)
    FROM gis.gis_layer WHERE id = '${LAYER_ID}';
  "

  # Feature rows via a temp staging table so the COPY column types match
  # exactly what we're writing (text, text, jsonb) — geometry is decoded after.
  cat <<'STAGE'

CREATE TEMP TABLE _stg_features (layer_id text, geom_ewkt text, props jsonb);

COPY _stg_features (layer_id, geom_ewkt, props) FROM stdin WITH (FORMAT text, DELIMITER E'\t');
STAGE

  # The actual COPY rows.
  psql_in -c "
    COPY (
      SELECT layer_id, ST_AsEWKT(geom), props
        FROM gis.gis_feature WHERE layer_id = '$LAYER_ID'
    ) TO STDOUT WITH (FORMAT text, DELIMITER E'\t');
  "

  cat <<FOOT
\\.

INSERT INTO gis.gis_feature (layer_id, geom, props)
SELECT layer_id,
       ST_GeomFromEWKT(geom_ewkt)::geometry(Geometry, 4326),
       props
  FROM _stg_features;

DROP TABLE _stg_features;

UPDATE gis.gis_layer
   SET feature_count = (SELECT count(*) FROM gis.gis_feature WHERE layer_id = '${LAYER_ID}')
 WHERE id = '${LAYER_ID}';

COMMIT;

-- VACUUM cannot run inside a transaction block, so it follows COMMIT.
VACUUM ANALYZE gis.gis_feature;

\\echo '✓ Restored DENUE ${STATE_NAME} (${VINTAGE}) — layer ${LAYER_ID}'
SELECT id, feature_count FROM gis.gis_layer WHERE id = '${LAYER_ID}';
FOOT
} > "$PLAIN"

ok "wrote $PLAIN ($(du -h "$PLAIN" | cut -f1))"

if [[ "$FORMAT" == "plain" ]]; then
  rm -f "$GZ"
  printf '\n\033[1;32m✓ Export done.\033[0m  %s\n' "$PLAIN"
else
  step "gzip"
  gzip -9 -f "$PLAIN"
  ok "wrote $GZ ($(du -h "$GZ" | cut -f1))"
  printf '\n\033[1;32m✓ Export done.\033[0m  %s\n' "$GZ"
fi
