#!/usr/bin/env bash
# Build a single rolled-up dump containing every state's features under one
# layer (lyr_denue_mx), so users who want "the whole country in one shot"
# can restore from a single artifact.
#
# Implementation: same staging-table pattern as export_state_dump.sh, but
# the COPY pulls from ALL lyr_denue_* layers and rewrites layer_id to
# 'lyr_denue_mx'. The dataset row carries vintage + national metadata; per-
# state provenance lives in feature.props.cve_ent (INEGI entity code,
# which the source already carries).
#
# Usage:
#   ./export_rollup.sh        → dist/denue_mx.sql.gz
#   ./export_rollup.sh plain  → dist/denue_mx.sql

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

FORMAT="${1:-gz}"
require_container

DATASET_ID="ds_denue_mx_$(jq -r '.source.vintage' "$GIS_CATALOG")"
DATASET_SLUG="denue-mx-$(jq -r '.source.vintage' "$GIS_CATALOG")"
DATASET_NAME="DENUE — Mexico (rolled-up, $(jq -r '.source.vintage' "$GIS_CATALOG"))"
LAYER_ID="lyr_denue_mx"
LAYER_NAME="DENUE points — Mexico (all 32 entities)"
VINTAGE=$(jq -r '.source.vintage' "$GIS_CATALOG")

step "Build national rollup dump → ${LAYER_ID}"

# Verify every per-state layer is loaded.
# state_ids clobbers DATASET_ID/DATASET_SLUG/DATASET_NAME/LAYER_ID/LAYER_NAME
# per call, so we stash + restore them around the loop. Pre-2026-05-22 a
# fragile partial-restore left the rollup INSERT pointing at whichever state
# came last — the resulting dataset/layer ids were wrong on Neon for hours.
SAVED_DATASET_ID="$DATASET_ID"
SAVED_DATASET_SLUG="$DATASET_SLUG"
SAVED_DATASET_NAME="$DATASET_NAME"
SAVED_LAYER_ID="$LAYER_ID"
SAVED_LAYER_NAME="$LAYER_NAME"
mapfile -t CODES < <(state_codes_all)
MISSING=()
for code in "${CODES[@]}"; do
  state_ids "$code"
  COUNT=$(psql_in -tA -c "SELECT COALESCE(feature_count,0) FROM gis.gis_layer WHERE id='${LAYER_ID}';" 2>/dev/null || echo 0)
  [[ "${COUNT:-0}" -gt 0 ]] || MISSING+=("$code")
done
DATASET_ID="$SAVED_DATASET_ID"
DATASET_SLUG="$SAVED_DATASET_SLUG"
DATASET_NAME="$SAVED_DATASET_NAME"
LAYER_ID="$SAVED_LAYER_ID"
LAYER_NAME="$SAVED_LAYER_NAME"
if (( ${#MISSING[@]} > 0 )); then
  warn "missing state layers: ${MISSING[*]} — rollup will skip them"
fi

TOTAL=$(psql_in -tA -c "SELECT count(*) FROM gis.gis_feature WHERE layer_id LIKE 'lyr_denue_%' AND layer_id <> 'lyr_denue_mx';")
ok "rolling up $TOTAL features across $((32 - ${#MISSING[@]})) states"

OUT_BASE="$GIS_DIST_DIR/denue_mx"
PLAIN="$OUT_BASE.sql"
GZ="$OUT_BASE.sql.gz"
rm -f "$PLAIN" "$GZ"

{
  cat <<HDR
-- =====================================================================
-- DENUE — Mexico (rolled-up, ${VINTAGE})
-- Generated by docuget-gis-data ($(date -u +%Y-%m-%dT%H:%M:%SZ))
--
-- Source: INEGI. Directorio Estadístico Nacional de Unidades Económicas
--         (DENUE). Términos de Libre Uso.
--         https://www.inegi.org.mx/inegi/terminos.html
--
-- Restore:
--     CREATE DATABASE mexico;
--     \\connect mexico
--     CREATE EXTENSION IF NOT EXISTS postgis;
--     \\i denue_mx.sql
-- =====================================================================

BEGIN;

CREATE SCHEMA IF NOT EXISTS gis;
SET search_path = public, gis;

CREATE TABLE IF NOT EXISTS gis.gis_dataset (
  id          text PRIMARY KEY,
  company_id  text NOT NULL DEFAULT 'public',
  slug        text NOT NULL,
  name        text NOT NULL,
  source      text NOT NULL,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, slug)
);

CREATE TABLE IF NOT EXISTS gis.gis_layer (
  id              text PRIMARY KEY,
  dataset_id      text NOT NULL REFERENCES gis.gis_dataset(id) ON DELETE CASCADE,
  name            text NOT NULL,
  geometry_type   text NOT NULL,
  srid            int  NOT NULL DEFAULT 4326,
  schema          jsonb NOT NULL DEFAULT '{}'::jsonb,
  feature_count   bigint NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gis.gis_feature (
  id          bigserial PRIMARY KEY,
  layer_id    text NOT NULL REFERENCES gis.gis_layer(id) ON DELETE CASCADE,
  geom        geometry(Geometry, 4326),
  props       jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS gis_feature_geom_gix  ON gis.gis_feature USING GIST (geom);
CREATE INDEX IF NOT EXISTS gis_feature_layer_idx ON gis.gis_feature (layer_id);

DELETE FROM gis.gis_feature WHERE layer_id = '${LAYER_ID}';
DELETE FROM gis.gis_layer   WHERE id       = '${LAYER_ID}';
DELETE FROM gis.gis_dataset WHERE id       = '${DATASET_ID}';

INSERT INTO gis.gis_dataset (id, company_id, slug, name, source, metadata)
VALUES (
  '${DATASET_ID}',
  'public',
  '${DATASET_SLUG}',
  '${DATASET_NAME}',
  'denue',
  jsonb_build_object(
    'license',     'INEGI — Términos de Libre Uso',
    'license_url', 'https://www.inegi.org.mx/inegi/terminos.html',
    'citation',    'INEGI. Directorio Estadístico Nacional de Unidades Económicas (DENUE).',
    'vintage',     '${VINTAGE}',
    'scope',       'national',
    'note',        'Per-feature entity codes are in props.cve_ent (01..32).'
  )
);

INSERT INTO gis.gis_layer (id, dataset_id, name, geometry_type, srid)
VALUES ('${LAYER_ID}', '${DATASET_ID}', '${LAYER_NAME}', 'point', 4326);

CREATE TEMP TABLE _stg_features (layer_id text, geom_ewkt text, props jsonb);

COPY _stg_features (layer_id, geom_ewkt, props) FROM stdin WITH (FORMAT text, DELIMITER E'\t');
HDR

  # The COPY rows: pull every per-state layer's features, rewrite layer_id.
  psql_in -c "
    COPY (
      SELECT '${LAYER_ID}', ST_AsEWKT(geom), props
        FROM gis.gis_feature
       WHERE layer_id LIKE 'lyr_denue_%' AND layer_id <> '${LAYER_ID}'
    ) TO STDOUT WITH (FORMAT text, DELIMITER E'\t');
  "

  cat <<FOOT
\\.

INSERT INTO gis.gis_feature (layer_id, geom, props)
SELECT layer_id,
       ST_GeomFromEWKT(geom_ewkt)::geometry(Geometry, 4326),
       props
  FROM _stg_features;

DROP TABLE _stg_features;

UPDATE gis.gis_layer
   SET feature_count = (SELECT count(*) FROM gis.gis_feature WHERE layer_id = '${LAYER_ID}')
 WHERE id = '${LAYER_ID}';

COMMIT;

VACUUM ANALYZE gis.gis_feature;

\\echo '✓ Restored DENUE — Mexico (${VINTAGE}) — layer ${LAYER_ID}'
SELECT id, feature_count FROM gis.gis_layer WHERE id = '${LAYER_ID}';
FOOT
} > "$PLAIN"

ok "wrote $PLAIN ($(du -h "$PLAIN" | cut -f1))"

if [[ "$FORMAT" == "plain" ]]; then
  rm -f "$GZ"
  printf '\n\033[1;32m✓ Rollup done.\033[0m  %s\n' "$PLAIN"
else
  step "gzip -9"
  gzip -9 -f "$PLAIN"
  ok "wrote $GZ ($(du -h "$GZ" | cut -f1))"
  printf '\n\033[1;32m✓ Rollup done.\033[0m  %s\n' "$GZ"
fi
